version: "3"

services:

  dred:
    image: dredgerzone:localdredger
    build:
      context: ../../../
      args:
        RUNNER_IMAGE: alpine:3.15
        GO_VERSION: 1.18
    volumes:
      - ./scripts/start.sh:/home/dredger/start.sh
      - $HOME/.dredger/:/home/dredger/.dredger/
    entrypoint:
      - /home/dredger/start.sh
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
