version: "3"
services:
  dred1:
    image: dredzone:dredger
    volumes:
      - ../state/dred1:/home/dredger/.dredger
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  hermes:
    image: dredzone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ../state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer:
    image: dredzone:relayer
    volumes:
      - ../state/relayer:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "dredger-host" ]
